version: "3.4"

services:

  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      # - redisdata:/data
      - /home/docsadmin/paperless/broker:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - /home/docsadmin/paperless/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      # - data:/usr/src/paperless/data
      # - media:/usr/src/paperless/media
      # - ./export:/usr/src/paperless/export
      # - /home/docsadmin/paperless-ngx/consume:/usr/src/paperless/consume
      - /mnt/docs/paperless/data:/usr/src/paperless/data
      - /mnt/docs/paperless/media:/usr/src/paperless/media
      - /mnt/docs/paperless/export:/usr/src/paperless/export
      - /mnt/docs/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_URL: http://docs-1.home
      PAPERLESS_TIME_ZONE: Australia/Sydney
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998


# volumes:
#   data:
#   media:
#   pgdata:
#   redisdata:
